version: "3"

services:
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    env_file:
      - .env
    environment:
      SONAR_JDBC_URL: "jdbc:postgresql://db:5432/$POSTGRES_DB"
      SONAR_JDBC_USERNAME: "$POSTGRES_USER"
      SONAR_JDBC_PASSWORD: "$POSTGRES_PASSWORD"
    ports:
      - "9000:9000"

  db:
    image: postgres:13
    hostname: postgresql
    container_name: postgresql
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
