FROM node:latest as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install && npm audit fix
COPY . .
RUN npm run build

FROM nginx:stable-alpine as production
COPY --from=build /usr/src/app/out /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]